# to run compose
## docker compose -f docker/docker-compose.yaml up
version: '3'

services:
  angular-login-page:
    build: 
      context: ../
      dockerfile: docker/dockerfile
    ports:
      - 4200:4200
    container_name: angular-login-page
    volumes:
      - "/app/node_modules"
      - ../:/app