server:
  port: 8080

spring:
  application:
    name: spring-keycloak-server

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-keycloak-server
            client-secret: 53Ofi8jmuIblFXB5LR5rDwZQsUwRrPFX
            scope: openid

        provider:
          keycloak:
            issuer-uri: http://127.0.0.1:9090/realms/beck

      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9090/realms/beck

auth-server:
  keycloak:
    login-url: http://127.0.0.1:9090/realms/beck/protocol/openid-connect/token
    user-creation-url: http://127.0.0.1:9090/admin/realms/beck/users
    client-id: spring-keycloak-server
    client-secret: 53Ofi8jmuIblFXB5LR5rDwZQsUwRrPFX
    grant-type: password